# Generated by Django 5.2.5 on 2025-08-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0004_alter_campaign_options_alter_query_options_and_more'),
        ('question_answers', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('poll_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='campaign.query')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls', to='question_answers.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(max_length=255)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_results', to='question_answers.answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='poll.poll')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['query', 'is_active', 'starts_at', 'ends_at'], name='poll_poll_query_i_d8ce59_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['question'], name='poll_poll_questio_3cf844_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['query', 'title'], name='poll_poll_query_i_7731fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='chk_poll_window_valid'),
        ),
        migrations.AddIndex(
            model_name='pollresult',
            index=models.Index(fields=['poll', 'is_active', 'user_identifier'], name='poll_pollre_poll_id_7eff26_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresult',
            index=models.Index(fields=['poll', 'answer'], name='poll_pollre_poll_id_7f8545_idx'),
        ),
    ]
