# Generated by Django 5.2.5 on 2025-09-07 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        ('question_answers', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poll_results', to='question_answers.answer'),
        ),
    ]
