# Generated by Django 5.2.5 on 2025-08-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='plt_id',
            new_name='plt',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='user_id',
            new_name='user',
        ),
    ]
