# Generated by Django 5.2.5 on 2025-08-28 10:11

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_query'),
        ('social', '0002_platform_created_at_platform_modified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='social.platform'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='query',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='query',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['user', 'plt', 'name', 'is_active'], name='campaign_ca_user_id_3a9e35_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['campaign', 'search_term', 'created_at'], name='campaign_qu_campaig_82cb9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'plt', 'name'), name='uq_active_campaign_name_per_user_platform'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('search_term'), models.F('campaign'), condition=models.Q(('is_active', True)), name='uq_active_query_per_campaign'),
        ),
    ]
