# Generated by Django 5.2.5 on 2025-09-07 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_options_alter_query_options_and_more'),
        ('poll', '0001_initial'),
        ('social', '0003_alter_platform_options_remove_platform_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResults',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_data', models.JSONField(blank=True, null=True)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('firescore', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('plt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='social.platform')),
                ('poll_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_results', to='poll.pollresult')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='campaign.query')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
