# Generated by Django 5.2.5 on 2025-09-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_queryresults'),
        ('poll', '0003_pollresult_uq_active_result_per_user_per_poll'),
        ('social', '0006_alter_userplatformconnection_external_account_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='queryresults',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('query', 'plt', 'source_id'), name='uq_active_source_per_query_platform'),
        ),
    ]
