# Generated by Django 5.2.5 on 2025-11-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_queryresults_uq_active_source_per_query_platform'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queryresults',
            name='uq_active_source_per_query_platform',
        ),
    ]
