# Generated by Django 5.2.5 on 2025-08-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='question_an_is_acti_5e42f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_answers.question')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'is_active'], name='question_an_questio_77c60e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'answer'), name='uq_active_answer_per_question')],
            },
        ),
    ]
