# Generated by Django 5.2.5 on 2025-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('plt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=200)),
                ('webpage', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
