# Generated by Django 5.2.5 on 2025-08-28 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_platform_created_at_platform_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='platform',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='webpage',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['is_active', 'name'], name='social_plat_is_acti_618130_idx'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='uq_active_platform_name'),
        ),
    ]
