# Generated by Django 5.2.5 on 2025-09-16 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_platform_options_remove_platform_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatformApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('upa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apps', to='social.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlatformConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('upc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_account_id', models.CharField(max_length=255)),
                ('external_username', models.CharField(blank=True, max_length=255)),
                ('oauth_version', models.CharField(choices=[('oauth2', 'OAuth2'), ('oauth1a', 'OAuth1a'), ('app', 'AppOnly')], default='oauth2', max_length=8)),
                ('bearer_token', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_secret', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=32)),
                ('scope', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='social.userplatformapp')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='social.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userplatformapp',
            index=models.Index(fields=['user', 'platform', 'is_active'], name='social_user_user_id_63878d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplatformapp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'platform'), name='uq_active_app_per_user_platform'),
        ),
        migrations.AddIndex(
            model_name='userplatformconnection',
            index=models.Index(fields=['user', 'platform', 'is_active'], name='social_user_user_id_e28f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='userplatformconnection',
            index=models.Index(fields=['user', 'platform', 'external_account_id', 'is_active'], name='social_user_user_id_b1f873_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplatformconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'platform', 'external_account_id'), name='uq_active_connection_per_user_platform_account'),
        ),
    ]
