# Generated by Django 5.2.5 on 2025-09-17 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_userplatformapp_userplatformconnection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userplatformconnection',
            name='uq_active_connection_per_user_platform_account',
        ),
        migrations.RemoveIndex(
            model_name='userplatformconnection',
            name='social_user_user_id_b1f873_idx',
        ),
        migrations.AddIndex(
            model_name='userplatformconnection',
            index=models.Index(fields=['platform', 'oauth_version', 'is_active'], name='social_user_platfor_66ad10_idx'),
        ),
        migrations.AddIndex(
            model_name='userplatformconnection',
            index=models.Index(fields=['platform', 'external_account_id', 'is_active'], name='social_user_platfor_44e387_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplatformconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'platform', 'external_account_id', 'oauth_version'), name='uq_active_connection_per_user_platform_account_auth'),
        ),
    ]
