# Generated by Django 5.2.5 on 2025-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_userplatformconnection_uq_active_connection_per_user_platform_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplatformconnection',
            name='external_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
